### ISSUE TITLE
How to use websocket in ALB using aws-alb-ingress-controller

### ISSUE THREAD

**Issue by vrathore18** [apollographql/subscriptions-transport-ws#710]
I am having a K8s setup in AWS which is working fine but due to some requirement I need to enable websocket in one of my application. I want to use subscriptions-transport-ws. 
Can someone provide me any documentation or sample how I can enable the websocket in the existing alb setup. below is my ingress definition.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "pd.frontend.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressScheme }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.external.acmCertificateARN }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ipWhiteList }}
spec:
  rules:
    - host: app.{{ .Values.domainName }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ template "pd.frontend.fullname" . }}
              servicePort: 80
```
Do I have to update the configuration on subscriptions-transport-ws as well to make it working?
